import hashlib
import time
from Crypto.Random import get_random_bytes

BLOCK_SIZE = 16


def generate_salt():
    return get_random_bytes(BLOCK_SIZE)


# https://stackoverflow.com/questions/3566176/salting-passwords-101
def generate_hash(secret_key):
    """Generates a hash value from a secret_key. The hash value is generated by hashing the secret_key and a salt value for
    15 seconds.
    :param secret_key: Secret key to be hashed
    :return: iter_counter, salt, hash_value
    """
    secret_key_bytes = secret_key.encode('utf-8')
    salt = generate_salt()
    key = b''.join([secret_key_bytes, salt])
    hash_value = b''

    start_time = time.time()
    iter_counter = 0

    # Calculate SHA256 value
    while time.time() - start_time <= 1:
        if iter_counter == 0:
            hash_value = hashlib.sha256(key).digest()
            iter_counter += 1
        hash_value = hashlib.sha256(hash_value).digest()
        iter_counter += 1
    return iter_counter, salt, hash_value


def find_hash(iter_counter, salt, secret_key):
    """Finds the hash value of a secret_key by iterating through the SHA256 hashing algorithm iter_counter times.
    :param iter_counter: Value to iterate through the SHA256 hashing algorithm
    :param salt: Salt value to be used in the SHA256 hashing algorithm
    :param secret_key: Secret key to be hashed
    :return: hash_value
    """
    i = 0
    key = b''.join([secret_key.encode('utf-8'), salt])
    hash_value = b''

    while i < iter_counter:
        if i == 0:
            hash_value = hashlib.sha256(key).digest()
            i += 1
        hash_value = hashlib.sha256(hash_value).digest()
        i += 1
    return hash_value
